#!/bin/sh

# tmux splitw -"${1}" -c "$(tmux run 'pwd')"
# currentpid=$2
# currentpath=$(readlink -f /proc/${currentpid}/cwd)
# tmux display "${currentpath} ${currentpid}"
# tmux splitw -${1} -c ${currentpath}
# tmux send-keys $(tmux display -p "#{pane_index}")
# tmux run -t $(tmux display -p "#{pane_index}") "tmux splitw -${1} -c $(pwd)"
# if [ "$(tmux display -p "#{pane_current_command}")" = "man" ]; then
	tmux splitw -${1} -c "#{pane_current_path}"
# fi
