import = ["~/.config/alacritty/tokyo_night.toml"]

[window]
opacity = 0.85
startup_mode = "Maximized"

option_as_alt = "Both"

[colors.cursor]
text = "#ffffff"
cursor = "#ffffff"


[font]
size = 12.0

[font.normal]
family = "MonaspiceAr Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "¥", chars = "\\" }
]
